### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. 

### ISSUE THREAD

**Issue by hellgelino** [sparkfun/BMPtoArray#2]
C:\Python\BMPtoArray-master>python bmp2array.py steam2.bmp
  File "bmp2array.py", line 42
    print "Size of file:", fileSize[0]
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Size of file:", fileSize[0])?

**Comment by aerickson** [comment]
The code isn't python 3 compatible yet, use python 2.

**Comment by nseidle** [comment]
Yep. Python 2. If we re-visit this some day we'll update to Python 3. 

We welcome PRs if anyone wants to help.

**Comment by aerickson** [comment]
https://github.com/sparkfun/BMPtoArray/pull/4
